# 数据集配置
DATASET:
    DATA_DIR: "./dataset/tusimple_lane_detection/"
    NUM_CLASSES: 2
    VIS_FILE_LIST: "dataset/tusimple_lane_detection/training/train_part.txt"
    TEST_FILE_LIST: "dataset/tusimple_lane_detection/training/val_part.txt"
    TRAIN_FILE_LIST: "dataset/tusimple_lane_detection/training/train_part.txt"
    VAL_FILE_LIST: "dataset/tusimple_lane_detection/training/val_part.txt"

# 预训练模型配置
MODEL:
    MODEL_NAME: "unet"
    DEFAULT_NORM_TYPE: "bn"

# 其他配置
TRAIN_CROP_SIZE: (512, 512)
EVAL_CROP_SIZE: (512, 512)
AUG:
    AUG_METHOD: "unpadding"
    FIX_RESIZE_SIZE: (512, 512)
    RICH_CROP:
        ENABLE: True
        ASPECT_RATIO: 0.0
        BLUR: True
        BLUR_RATIO: 0.1
        MAX_ROTATION: 0
        MIN_AREA_RATIO: 0.0
        BRIGHTNESS_JITTER_RATIO: 0.4
        CONTRAST_JITTER_RATIO: 0.4
        SATURATION_JITTER_RATIO: 0.4
BATCH_SIZE: 4
TRAIN:
    PRETRAINED_MODEL_DIR: "./pretrained_model/unet_bn_coco/"
    MODEL_SAVE_DIR: "./saved_model/unet_optic/"
    SNAPSHOT_EPOCH: 5
TEST:
    TEST_MODEL: "./saved_model/unet_optic/final"
SOLVER:
    NUM_EPOCHS: 10
    LR: 0.001
    LR_POLICY: "poly"
    OPTIMIZER: "adam"
